#!/bin/sh -e
#
# dotfiles repository download script
#
# Run with either command:
# curl -fsSL sh.nickficano.com | sh
# wget -qO- sh.nickficano.com | sh

# Exit if a dotfiles directory already exists
dotfiles_check() {
  if [ -d "$HOME/github/dotfiles" ]; then
    printf '\033[31mERROR:\033[0m ~/dotfiles already exists on this system.\n' >&2
    exit 1
  fi
}

main() {
  mkdir -p "$HOME/github"
  if ! [ -x "$(command -v git)" ]; then
    if [ -x "$(command -v curl)" ]; then
      curl -L https://github.com/nficano/dotfiles/archive/master.tar.gz -o "/tmp/dotfiles-master.tar.gz"
      tar xzf "/tmp/dotfiles-master.tar.gz"
      mv "/tmp/dotfiles-master" "$HOME/github/dotfiles"
    elif [ -x "$(command -v wget)" ]; then
      wget -O "/tmp/dotfiles-master.tar.gz" https://github.com/nficano/dotfiles/archive/master.tar.gz
      tar xzf "/tmp/dotfiles-master.tar.gz"
      mv "/tmp/dotfiles-master" "$HOME/github/dotfiles"
    fi
  else
    git clone --recursive https://github.com/nficano/dotfiles.git "$HOME/github/dotfiles"
  fi

  if [ -d "$HOME/github/dotfiles" ]; then
    printf '\033[32mSUCCESS:\033[0m Repository downloaded to ~/dotfiles\nNavigate to ~/github/dotfiles and run `make install`'
  else
    printf '\033[31mERROR:\033[0m dotfiles either not downloaded or not extracted successfully\n' >&2
    exit 1
  fi
}

dotfiles_check
main
