#!/usr/bin/env bash

# Quit System Preferences to avoid overriding
osascript -e 'tell application "System Preferences" to quit'

# Set Wallpaper
osascript -e "
tell application \"System Events\" 
    tell every desktop
        set picture to \"$HOME/github/dotfiles/wallpaper/The Cliffs.heic\"
    end tell
end tell"

# Cache the sudo credentials
sudo -v

# Prevent sudo from asking for password more than once
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done 2>/dev/null &

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Always show expanded save panel
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Always show expanded print panel
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Automatically quit printer app once all jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Remove duplicates in the "Open With" menu
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# Increase the Bluetooth sound quality
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# Prevent the keyboard media controls from opening iTunes
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2>/dev/null

# Disable the shadows in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Disable the file extension change warning
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Use the list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Expand the "General", "Open with", and "Sharing & Permissions" in File Info
defaults write com.apple.finder FXInfoPanesExpanded -dict \
  General -bool true \
  OpenWith -bool true \
  Privileges -bool true

# Minimize windows into their application icon
defaults write com.apple.dock minimize-to-application -bool true

# Disable show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Start TextEdit in plain-text mode
defaults write com.apple.TextEdit RichText -int 0

# Launch Activity Monitor to main window
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

# Set default dock size to 45 pixels
defaults write com.apple.dock "tilesize" -int "45" && killall Dock

# Enable AirDrop over Ethernet
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Show ~/Library folder
chflags nohidden "$(realpath ~/Library)"

# Hide unused app directories
chflags hidden /Users/nficano/Creative\ Cloud\ Files
chflags hidden /Users/nficano/Music
chflags hidden /Users/nficano/Movies
chflags hidden /Users/nficano/Pictures
chflags hidden /Users/nficano/Applications
chflags hidden /Users/nficano/Public

for app in "Activity Monitor" \
  "Address Book" \
  "Calendar" \
  "cfprefsd" \
  "Contacts" \
  "Dock" \
  "Finder" \
  "Google Chrome Canary" \
  "Google Chrome" \
  "Safari" \
  "Spectacle" \
  "SystemUIServer"; do
  killall "${app}" &>/dev/null
done
