#!/bin/bash

set -o errexit          # Exit on most errors (see the manual)
set -o errtrace         # Make sure any error trap is inherited
set -o nounset          # Disallow expansion of unset variables
set -o pipefail         # Use last non-zero exit code in a pipeline
#set -o xtrace          # Trace the execution of the script (debug)

is_installed() {
  if command -v "$1" > /dev/null; then
    return 0
  else
    return 1
  fi
}

install_package() {
  brew install "$1"
}

install_launchagent() {
    sed "s|\$HOME|${HOME}|g" com.nickficano.carbon.plist > "$HOME/Library/LaunchAgents/com.nickficano.carbon.plist"
}

install_script() {
    mkdir -p "$HOME/Library/com.nickficano"
    ln -fsn "$PWD/carbon.agent" "$HOME/Library/com.nickficano/carbon.agent"
}

log() {
  message="$1"
  shift
  # shellcheck disable=SC2059
  printf "$message\n" "$@"
}

run_setup() {
  if ! is_installed "unison"; then
    log "Installing Unison ..."
    install_package "unison"
  fi

  log "Installing carbon ..."
  install_script

  log "Installing carbon LaunchAgent ..."
  install_launchagent

  log "carbon Installed Successfully! 🍻"
  log "Logfile: $HOME/Library/Logs/com.nickficano.carbon.log"
}

run_setup
